### ISSUE TITLE
404 chosen.css not found

### ISSUE THREAD

**Issue by davehorton** [mishguruorg/angular-timezone-selector#1]
followed your build instructions, and it don't work.  From the server I get:

Failed to load resource: server responded with a status of (404 Not Found): http://localhost:9000/bower_components/chosen/chosen.css

This problem seems to appears because you only included chosen.min.css in the package that bower installs.

Am I doing something wrong here?

**Comment by ashokfernandez** [comment]
Are you sure that the bower_compenents folder is setup to be served properly by your local host server?

**Comment by davehorton** [comment]
Yes, I have other components under that folder and they are working well.  As I mentioned, the issue appears to the that there is no chosen.css under that folder (only a chosen.min.css)

**Comment by ashokfernandez** [comment]
Just had another look now, you shouldn't need to include chosen.css as the angular-timezone-selector.css file is built with all of the CSS from chosen that is needed.

**Comment by a-k-g** [comment]
This problem is actually happening because of - https://github.com/harvesthq/chosen/issues/2324 . If we are going with including the chosen.css in angular-timezone-selector.css, should we remove the dependency on chosen in our bower.json?

**Comment by ashokfernandez** [comment]
It needs to stay in bower.json so that it will be downloaded to be built into the CSS when a fresh install is done
