### ISSUE TITLE
TypeError: Cannot read property 'nOffset' of undefined

### ISSUE THREAD

**Issue by dpatinor** [mishguruorg/angular-timezone-selector#16]
The directive is in a modal, the second time I open the modal, is when the error occurs.

The error occurs if: display-utc = "true"

TypeError: Cannot read property 'nOffset' of undefined at link (http://localhost:9000/bower_components/angular-timezone-selector/dist/angular-timezone-selector.js:119:40)

Version: 1.2.2

**Comment by karlhaas** [comment]
Has been fixed in version 1.2.4.
See #9

**Comment by dpatinor** [comment]
Thank you!
