### ISSUE TITLE
The selector is not working in Internet Explorer

### ISSUE THREAD

**Issue by karlhaas** [mishguruorg/angular-timezone-selector#17]
As described in http://mzl.la/1ja08u0 String.prototype.includes is not supported in Internet Explorer.

The following Polyfill has to be added:

``` javascript
if (!String.prototype.includes) {
  String.prototype.includes = function() {'use strict';
    return String.prototype.indexOf.apply(this, arguments) !== -1;
  };
}
```

**Comment by ashokfernandez** [comment]
Fixed in https://github.com/mishguruorg/angular-timezone-selector/commit/cde81ca7e708fea5eed9145d82ec17dc8f0ed1f8
