### ISSUE TITLE
Modify so both underscore and lodash users can use

### ISSUE THREAD

**Issue by dustinsgoodman** [mishguruorg/angular-timezone-selector#21]
I was attempting to use your project earlier today and was required to ditch it due to its specific use of lodash. My team uses underscore instead which does not provide the same functionality as lodash. Specifically, the use of `_.get` [here](https://github.com/mishguruorg/angular-timezone-selector/blob/master/build/angular-timezone-selector.js#L160) is the main issue. If this call were replaced with something less specific to lodash, underscore users could use this package as well. Food for thought.

**Comment by ashokfernandez** [comment]
Happy to incorporate changes if you want to make a pull request
