### ISSUE TITLE
bower issue when adding angular-timezone-selector

### ISSUE THREAD

**Issue by wimdeblauwe** [mishguruorg/angular-timezone-selector#23]
I have added angular-timezone-selector in bower like this:

```
"angular-timezone-selector": "~1.4.3"
```

However, this gives a problem that bower does not know what version of angular to choose. As a workaround, I have added this to my bower.json file:

```
"resolutions": {
  "angular": "1.4.8"
}
```

Would be great if this could be avoided.

**Comment by wimdeblauwe** [comment]
While bower might be happy with the workaround, the browser is not. I get:

```
Uncaught ReferenceError: _ is not defined
   (anonymous function) 
```

Should this work with angular 1.4.8 or will there be updates needed?

**Comment by ashokfernandez** [comment]
I don't think this is as so much an issue with this package, but more so
with the combination of packages you're using. This module should be
compatible with most recent versions of angular.

**Comment by ashokfernandez** [comment]
Also the error you mentioned is from not having lodash installed correctly.

**Comment by wimdeblauwe** [comment]
This is my list of dependencies:

```
"dependencies": {
"angular": "~1.4.7",
"bootstrap": "components/bootstrap#~3.3.5",
"angular-route": "~1.4.7",
"jquery": "components/jquery#~2.1.4",
"angular-bootstrap": "angular-ui-bootstrap-bower#~0.14.2",
"angular-ui-router": "~0.2.15",
"angular-mocks": "~1.4.8",
"angular-datatables": "~0.5.2",
"angular-messages": "~1.4.8",
"angular-resource": "1.4.x",
"eonasdan-bootstrap-datetimepicker": "~4.17.37",
"angular-bootstrap-datetimepicker-directive": "~0.1.3",
"ng-token-auth": "~0.0.28",
"angular-loading-bar": "~0.8.0",
"angular-animate": "~1.4.8",
"ngMask": "angular-mask#~3.0.16",
"ng-file-upload": "~11.0.2",
"angular-ladda": "~0.3.1",
"angular-timezone-selector": "~1.4.3"
}
```

How do I add lodash?

**Comment by janhaum** [comment]
What version of lodash needs to be implemented? I'm troubling with the same problem.

**Comment by wimdeblauwe** [comment]
Adding:

 "ng-lodash": "~0.3.0",

to the "dependencies" fixes the issue (If you also add the "resolutions" section I wrote about above)
