### ISSUE TITLE
_.get is not a function

### ISSUE THREAD

**Issue by janhaum** [mishguruorg/angular-timezone-selector#24]
When I add angular-timezone-selector to my project with Bower I get this error:

`Error: _.get is not a function
.link@http://localhost:7777/assets/bower_components/angular-timezone-selector/angular-timezone-selector.js:160:28`

How can I correctly implement it into a project and what dependencies need to be installed? Please add it to your instructions.

A working example with the new files would be great.

**Comment by ashokfernandez** [comment]
Sounds like you don't have lodash properly installed. Maybe this [plunker demo](https://plnkr.co/edit/99qoqLYUlFVsaIHUbbT8?p=preview) can help you out.
