### ISSUE TITLE
Replace jstz.determine().name() with moment.tz.guess()

### ISSUE THREAD

**Issue by tlk** [mishguruorg/angular-timezone-selector#27]
First of all, thanks for open sourcing this project - it looks very promising.

I noticed that https://github.com/moment/moment-timezone/pull/285 added functionality to moment-timezone.js for guessing the user's timezone. Do you think this could replace https://github.com/HenningM/jstimezonedetect in order to limit the number of dependencies?

**Comment by ashokfernandez** [comment]
Looks promising, feel free to make the changes in a pull request
