### ISSUE TITLE
Type to filter and scroll on mobile (iOS and Android)

### ISSUE THREAD

**Issue by sgilroy** [mishguruorg/angular-timezone-selector#30]
The directive does not behave well on mobile. I noticed the following problems
- For iPhone and Android, the type to filter is not accessible. Tapping brings up the full select list.
- iPad allows you to type to filter, but scrolling the list does not seem to work.

I have tested both in the browser (mobile Safari/Chrome) and in a hybrid Cordova app (WebKit).

Is this a known issue? Is there a workaround or plans to resolve it?

**Comment by ashokfernandez** [comment]
Hi, this is a known issue but currently I don't have the time to look into it. You're welcome to have a go at fixing it and submitting a pull request.

**Comment by suryasingh** [comment]
the issue is due to chosen , as chosen is not supported on moblie .. @ashokfernandez we can go for jquery select2

**Comment by ashokfernandez** [comment]
Will have a look into it. If anyone wants to create a branch and try it out that would be cool too.
