### ISSUE TITLE
Update the libraries

### ISSUE THREAD

**Issue by AhsanAyaz** [mishguruorg/angular-timezone-selector#31]
Please update the libraries associated with the plugin
Most of them are deprecated and cause issues

I'm working on a project which has both lodash and underscorejs (latest) 
And I've had to place hacks to get things working 
 :)

**Comment by ashokfernandez** [comment]
Feel free to make a pull request with the changes if you think everyone will benefit from them

**Comment by AhsanAyaz** [comment]
Sure :+1:
