### ISSUE TITLE
Disable timezone-selector

### ISSUE THREAD

**Issue by SmailHammour** [mishguruorg/angular-timezone-selector#34]
Hi,

Is there any way to disable the timezone-selector? I tried applying ng-disabled on the element but it doesn't work.

**Comment by ashokfernandez** [comment]
There isn’t a way to do this yet but it should be possible as long as there
is a way to disable the chosen selector it’s built with.

**Comment by nolines** [comment]
+1

**Comment by Aknilam** [comment]
+1
