### ISSUE TITLE
show/set-local does not work

### ISSUE THREAD

**Issue by cpursley** [mishguruorg/angular-timezone-selector#35]
Demo: https://plnkr.co/edit/Jk9Zwkx8sq3Xv8gJIM27?p=preview

Perhaps this is an issue with moment.js ?

**Comment by jfrumar** [comment]
You're missing the jsTimezoneDetect dependency. I added it here:

https://plnkr.co/edit/aec1snhy2HLse5MzIVrS?p=preview

You'll see now that the error is `_.where is not a function` because _.where was deprecated in favor of _.filter in lodash. I'll create a PR.

**Comment by karlhaas** [comment]
see #29

**Comment by ashokfernandez** [comment]
Fixed and released as v1.6.0
