### ISSUE TITLE
vendor.min.js:59 Uncaught ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by nolines** [mishguruorg/angular-timezone-selector#38]
This method throws an error. 

.constant('_', _)
  .constant('moment', moment)
  .factory('timezoneFactory', ['_', 'moment', function (_, moment) {
    return {
      get: function () {
        var timezoneMap = {}
        _.forEach(moment.tz.names(), function (zoneName) {
          var tz = moment.tz(zoneName)
          timezoneMap[zoneName] = {
            id: zoneName,
            name: zoneName.replace(/_/g, ' '),
            offset: 'UTC' + tz.format('Z'),
            nOffset: tz.utcOffset()
          }
        })
        return timezoneMap
      }
    }
  }])

**Comment by ashokfernandez** [comment]
Looks like you don't have lodash installed or your build system is removing underscores. If you have a look at [the built file here](https://github.com/mishguruorg/angular-timezone-selector/blob/master/build/angular-timezone-selector.js) you'll see that  the code should be like this

```
  .constant('_', _)
  .constant('moment', moment)
  .factory('timezoneFactory', ['_', 'moment', function (_, moment) {
```

Note how the one you pasted is missing underscores

**Comment by nolines** [comment]
thanks for your response.
