### ISSUE TITLE
demo: jstz is not defined

### ISSUE THREAD

**Issue by Aknilam** [mishguruorg/angular-timezone-selector#41]
`jstz is not defined` error when adding `show-local="true"`

https://plnkr.co/edit/rhuHCR0IUg0wHFutAuKd?p=preview

**Comment by ashokfernandez** [comment]
Should be fixed now

https://plnkr.co/edit/99qoqLYUlFVsaIHUbbT8?p=preview

**Comment by pranjayvirgo** [comment]
the timezone options are not getting populated.Debugged the issue.Seems to zoneToCC ,CCToCountryName not getting populated from CSV .I am using webjars to include js dependency.Can you please help.

**Comment by ashokfernandez** [comment]
The CSV data is built into the file before it's distributed, are you sure you're using the prebuilt file in the `dist` folder?

https://github.com/mishguruorg/angular-timezone-selector/blob/master/dist/angular-timezone-selector.js

**Comment by pranjayvirgo** [comment]
Hi ashok,

Thanks for reply we were pointing to the wrong file in webjar.

Thanks
Pranjay
