### ISSUE TITLE
Issue While Scrolling

### ISSUE THREAD

**Issue by deveshsatija** [mishguruorg/angular-timezone-selector#47]
Hi,

There seems to be an issue with drop down. When the drop down is opened and i try to scroll down the list using mouse scroller, its behaving abruptly. Sometimes it takes me directly to the bottom of the list and if i am at bottom of the list and tries to go up the list (using mouse scroller) its taking me back to the bottom again and again.

I have verified this issue in the plunkr linked also - https://plnkr.co/edit/99qoqLYUlFVsaIHUbbT8?p=preview 

I have seen this issue on un-minified and minified code both. And in both firefox and chrome.

So for reproducing this, click on the input box so that drop down is opened and use the mouse scroller to select any timezone which is somewhere in middle of the drop down. Or go to the bottom of the list and try  to select the timezone in middle of list using mouse scroller.

**Comment by ryan-mccaffrey** [comment]
Commenting to follow. Also having this issue.
