### ISSUE TITLE
Angular-timezone-selector Failed to instantiate module starter

### ISSUE THREAD

**Issue by thadeuszlay** [mishguruorg/angular-timezone-selector#54]
angular-timezone-selector doesn't work correclty.

During installation of the package I got this message:

>  Unable to find a suitable version for angular, please choose one by typing one of the numbers below:
>     1) angular#~1.3.8 which resolved to 1.3.20 and is required by angular-timezone-select#1.1.3
>     2) angular#1.5.3 which resolved to 1.5.3 and is required by ionic#1.3.1, ionic#1.3.1
>     3) angular#>= 1.0.8 which resolved to 1.5.8 and is required by angular-ui-router#0.2.13

It offered me 3 options. I choosed them one by one and tested them. In all 3 cases I got the same error as described below:

After deploying the app with `ionic serve --lab` on the browser, It says:

> $injector:modulerr] Failed to instantiate module starter due to:
> Error: [$injector:modulerr] Failed to instantiate module angular-timezone-selector due to:
> Error: [$injector:nomod] Module 'angular-timezone-selector' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

In my app.js I included the module like this:

```
angular.module('starter', ['ionic',
    'starter.controllers', 'starter.services', 'ion-datetime-picker',
    'angular-timezone-selector'
  ])
```

My bower.json looks like this:

```
{
  "name": "HelloIonic",
  "private": "true",
  "devDependencies": {
    "ionic": "driftyco/ionic-bower#1.3.1"
  },
  "dependencies": {
    "ion-datetime-picker": "^0.4.0"
  },
  "resolutions": {
    "angular": "~1.3.8"
  }
}
```

I updated the angular resoltions from "~1.3.8" to "~1.3.x", so it would suppress the notification in the beginning but still the error persists.

**Comment by ashokfernandez** [comment]
Have you tried running a fresh install from bower? Module not available sounds like the code for it isn't actually being bundled into your build.

**Comment by thadeuszlay** [comment]
@ashokfernandez : Yes, I did. I created a new ionic project (tabs template). added android platform. Build it. installed the plugin. Then ran it, but it would show the same error in the console.

**Comment by ashokfernandez** [comment]
Closing as this seems like an issue specific to using this with Ionic. Feel free to post in here if you did find a solution to this.
