### ISSUE TITLE
Expects _ to be available in global scope.

### ISSUE THREAD

**Issue by jkndrkn** [mishguruorg/angular-timezone-selector#55]
I am working with a project where we use lodash without placing "_" in global scope. This allows us to import only those functions that we are actually using instead of having to bundle the entire library in our published code.

Without "_" in global scope, this application is issuing the following error:

    angular-timezone-selector.js:14 Uncaught ReferenceError: _ is not defined
    at http://localhost:8080/testing/node_modules/angular-timezone-selector/angular-timezone-selector.js:14:18(anonymous function) @ angular-timezone-selector.js:14

Here is the relevant line of code: https://github.com/mishguruorg/angular-timezone-selector/blob/master/angular-timezone-selector.js#L14

**Comment by ashokfernandez** [comment]
Feel free to make a PR with a fix to this if you come up with a way around it

**Comment by javeedrahman** [comment]
Any update on this issues, i am still having this issues. i have installed via npm
