### ISSUE TITLE
Link on npmjs.com page is broken

### ISSUE THREAD

**Issue by jkndrkn** [mishguruorg/angular-timezone-selector#56]
The github project link on the [npmjs.com page](https://www.npmjs.com/package/angular-timezone-selector) for this project points to https://github.com/mishguruorg/angular-country-selector/ instead of https://github.com/mishguruorg/angular-timezone-selector/

**Comment by ashokfernandez** [comment]
I didn't push this to NPM, it looks like @saike has published this to NPM. @saike can you add me to the collaborators list on NPM or can you please update this?

**Comment by saike** [comment]
@ashokfernandez, yes i published. Give me your nickname on npmjs.com, i will add you.

**Comment by ashokfernandez** [comment]
Thanks @saike, I'm @ashokfernandez on NPM - https://www.npmjs.com/~ashokfernandez

**Comment by saike** [comment]
ok i added you, and i can leave this package now?

**Comment by ashokfernandez** [comment]
You can leave or stay, up to you!

**Comment by saike** [comment]
i removed me from this package

**Comment by ashokfernandez** [comment]
No problem
