### ISSUE TITLE
no results. try searching for the name of your country or nearest major city

### ISSUE THREAD

**Issue by Mr-Anonymous** [mishguruorg/angular-timezone-selector#57]
The timezone selector in my app does not show the countries in the drop down. Instead it gives the message:
```
no results. try searching for the name of your country or nearest major city
```

In my app, after the gulp compilation, the js files gets added in this order:
```
'/js/jquery/jquery-2.1.4.min.js',
'/js/bootstrap/bootstrap.min.js',
'/js/angular/angular.min.js',
'/js/angular/angular-animate.min.js',
'/js/ui-router/angular-ui-router.min.js',
'/js/bootstrap/ui-bootstrap-tpls-0.13.4.min.js',
'/js/plugins/lodash/lodash.min.js',
'/js/plugins/moment/moment.min.js',
'/js/plugins/moment/moment-timezone.min.js',
'/js/plugins/chosen/chosen.jquery.min.js',
'/js/plugins/chosen/jstz.min',
'/js/plugins/chosen/angular-timezone-selector.min',
```
Module dependency added like this:
```
angular.module('timezoneSelectExample', ['angular-timezone-selector']);
```
Then it is added to my html like this:
```
<timezone-selector ng-model="vm.timezone">
```
The above directive shows the Chosen input box with the placeholder "Choose a timezone".

When I click on the input field, the drop down has only the search icon with no list. When I type something I get the message:
```
no results. try searching for the name of your country or nearest major city
```
What am I missing to get this working?

**Comment by Mr-Anonymous** [comment]
It appears, the version of `moment-timezone.js` was the reason for this not working. I had the latest version of this file `version : 0.5.9`. When I changed it back to the version in your demo `version : 0.5.0` it started working. After this change, the directive works the way it should.

Last question, with lodash, the latest version downloaded from their website seems to be different from the old you had linked. The current version start with comment `Underscore.js 1.8.3`. Should it matter if I use this version or use the particular one from your Plunker demo? It seems to be working now.

**Comment by ashokfernandez** [comment]
Use the one in the plunkr demo, I think that version of underscore is there from someone who was trying to add underscore compatibility to this repo

**Comment by Mr-Anonymous** [comment]
Thank you @ashokfernandez. Will change to the plunkr version of underscore.
