### ISSUE TITLE
not working with angular 1.6.3

### ISSUE THREAD

**Issue by horiaIon** [mishguruorg/angular-timezone-selector#65]
Hi, i've updated angular version to 1.6.3 and is not working. See
https://plnkr.co/edit/dW8qA9sL6A2PmhGzzkI6?p=preview
Is not binding on the model anymore.

Thx,
Horia.

**Comment by horiaIon** [comment]
closing because there is another one opened
https://github.com/mishguruorg/angular-timezone-selector/issues/60
didn't see it :)

**Comment by Signido** [comment]
why closed ??? do you have any update for the great control work with 1.64 ?
