### ISSUE TITLE
underscore.js dependency required?

### ISSUE THREAD

**Issue by v29neil** [mishguruorg/angular-timezone-selector#7]
ReferenceError: _ is not defined
.constant('_', _)

I am getting this error while using the demo code. 
After searching i guess it need underscore.js library?
Is it required? 
Its not mentioned in description about the dependency of underscore js.

**Comment by wassname** [comment]
I think that's lodash which has superseeded underscore. Lodash is in the dependencies in bower.json, so you need to load all the dependencies. An example of the order is in the "<b>" element [here](http://mishguruorg.github.io/angular-timezone-selector/). Hope this helps.
