### ISSUE TITLE
Show Local fails when local city has spaces

### ISSUE THREAD

**Issue by w1llywonka** [mishguruorg/angular-timezone-selector#8]
In the timezones factory (line 16: name: zoneName.replace(/_/g, ' '),) underscores are stripped, but then in the timezoneSelector directive, timezones are searched using a string that may contain underscores (line 98: var extraTZs = _.where(timezones,{'name':jstz.determine().name() });).

**Comment by ashokfernandez** [comment]
Should be fixed with https://github.com/mishguruorg/angular-timezone-selector/commit/5a73830eadecdb63480f2a2ccc55849634568168
